services:
  monica:
    container_name: monicaCRM
    image: monica
    depends_on:
      - db
    ports:
      - 5858:80
    environment:
      - APP_KEY=XhaK2HC8BKir6BuWhpiNPOCTWGdlzKuNWneZTp2QKZ8= # Generate with `echo -n 'base64:'; openssl rand -base64 32`
      - DB_HOST=db
      - DB_USERNAME=monica
      - DB_PASSWORD=secret
    volumes:
      - /APPDATA/monica/storage:/var/www/html/storage
    restart: unless-stopped
  db:
    image: mariadb:11
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=monica
      - MYSQL_USER=monica
      - MYSQL_PASSWORD=secret
    volumes:
      - mysql:/var/lib/mysql
    restart: unless-stopped
    depends_on:
      - monica

volumes:
  data:
    name: data
  mysql:
    name: mysql
