services:
  myspeed:
    image: germannewsmaker/myspeed:latest
    container_name: myspeed
    ports:
      - "5216:5216"
    restart: unless-stopped
    volumes:
      - "/DATA/AppData/myspeed/config:/myspeed/config"
      - "/DATA/AppData/myspeed/data:/myspeed/data"
