name: diun
services:
  diun:
    image: crazymax/diun:latest
    command: serve
    volumes:
      - "./data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./diun.yml:/diun.yml:ro"
    environment:
      - "TZ=Europe/Paris"
      - "DIUN_WATCH_WORKERS=20"
      - "DIUN_WATCH_SCHEDULE=0 */6 * * *"
      - "DIUN_WATCH_JITTER=30s"
      - "DIUN_PROVIDERS_DOCKER=true"
      ## Aqui colocamos la configuracion para envio de notificaciones por telegram
      - "DIUN_NOTIFIERS_TELEGRAM=true"
      - "DIUN_NOTIF_TELEGRAM_TOKEN="
      - "DIUN_NOTIF_TELEGRAM_CHATID=[\"891256734:25;12\"]"
    labels:
      - "diun.enable=true"
    restart: always

